### ISSUE TITLE
Use of astropy.model.tabular2D

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#227]
asdf unconditionally uses `astropy.model.tabular2D`, which is only introduced in the not yet released version 1.3 of astropy. With the current version 1.2.1 of astropy, the tests will consequently fail:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "asdf/__init__.py", line 37, in <module>
    from .asdf import AsdfFile
  File "asdf/asdf.py", line 15, in <module>
    from . import block
  File "asdf/block.py", line 26, in <module>
    from . import stream
  File "asdf/stream.py", line 6, in <module>
    from .tags.core import ndarray
  File "asdf/tags/__init__.py", line 11, in <module>
    from . import transform
  File "asdf/tags/transform/__init__.py", line 10, in <module>
    from .tabular import *
  File "asdf/tags/transform/tabular.py", line 15, in <module>
    class TabularType(TransformType):
  File "asdf/tags/transform/tabular.py", line 18, in TabularType
    types = [astropy.modeling.models.Tabular2D,
AttributeError: 'module' object has no attribute 'Tabular2D'
```
Please wrap the according code with some version check of astropy, or depend on a minimal version of astropy (once the 1.3 is released). Note however that relying on the newest features will make backporting to older OS versions more difficult (since astropy needs to be backported first).

**Comment by nden** [comment]
Duh! I'll make 1.2.1 fixing this. Thanks for the note!

**Comment by nden** [comment]
@olebole  I've uploaded 1.2.1 to pypi. It runs with older versions of astropy.

**Comment by olebole** [comment]
Thanks, it is now uploaded to Debian as well.
