### ISSUE TITLE
Automatically install dependencies

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#251]
The following dependencies need to be installed manually when buildng `asdf` in a clean environment:
* `pyyaml`
* `psutil`
* `pytest`

**Comment by drdavella** [comment]
This appears to already be the case. `psutil` is only required if running the tests with `--open-files`

**Comment by drdavella** [comment]
I'm reopening this. Here's what happens to me in a clean environment (after installing astropy) with both Python 2.7 and 3.6. The command is `./setup.py test`, so it seems like maybe we need to make sure we install before testing?

>running test
Searching for jsonschema>=2.3.0
Best match: jsonschema 2.6.0
Processing jsonschema-2.6.0-py3.6.egg
Using /home/ddavella/asdf/.eggs/jsonschema-2.6.0-py3.6.egg
Searching for pyyaml>=3.10
Best match: PyYAML 3.12
Processing PyYAML-3.12-py3.6-linux-x86_64.egg
Using /home/ddavella/asdf/.eggs/PyYAML-3.12-py3.6-linux-x86_64.egg
running build
running build_py
package init file 'asdf-standard/schemas/__init__.py' not found (or not a regular file)
package init file 'asdf-standard/reference_files/__init__.py' not found (or not a regular file)
Traceback (most recent call last):
  File "/tmp/asdf-test-hpbhwgyk/lib.linux-x86_64-3.6/asdf/__init__.py", line 23, in <module>
    import yaml as _
ModuleNotFoundError: No module named 'yaml'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/asdf-test-hpbhwgyk/lib.linux-x86_64-3.6/asdf/__init__.py", line 25, in <module>
    raise ImportError("asdf requires pyyaml")
ImportError: asdf requires pyyaml

**Comment by drdavella** [comment]
Closing again. This is only a problem when running the test in a clean environment. It is perfectly reasonable to expect users to have to build the software before testing.
