### ISSUE TITLE
[2.0.0] Tests fail with RepresenterError during build

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#498]
Hi,

When running the tests during the build of the package, many of them fail with a `RepresenterError`:

```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:217: cd /build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build; python3.6 -m pytest 
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
rootdir: /build/python-asdf-2.0.0, inifile: setup.cfg
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 272 items / 2 skipped

asdf/asdf.py .                                                           [  0%]
asdf/stream.py F                                                         [  0%]
asdf/util.py ...                                                         [  1%]
asdf/commands/tests/test_defragment.py FFs                               [  2%]
[...]
=================================== FAILURES ===================================
_________________________ [doctest] asdf.stream.Stream _________________________
012     Examples
013     --------
014     Save a double-precision array with 1024 columns, one row at a
015     time::
016 
017          >>> from asdf import AsdfFile, Stream
018          >>> import numpy as np
019          >>> ff = AsdfFile()
020          >>> ff.tree['streamed'] = Stream([1024], np.float64)
021          >>> with open('test.asdf', 'wb') as fd:
UNEXPECTED EXCEPTION: RepresenterError("cannot represent an object: {'streamed': Stream([1024], float64, strides=None), 'history': {'extensions': []}, 'asdf_library': {'
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest asdf.stream.Stream[4]>", line 2, in <module>

  File "/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/asdf.py", line 1059, in write_to
    self._serial_write(fd, pad_blocks, include_block_index)

  File "/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/asdf.py", line 820, in _serial_write
    self._write_tree(self._tree, fd, pad_blocks)

  File "/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/asdf.py", line 781, in _write_tree
    yamlutil.dump_tree(tree, fd, self)

  File "/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/yamlutil.py", line 336, in dump_tree
    tags=tags)

  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)

  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/yamlutil.py", line 78, in represent_data
    node = super(AsdfDumper, self).represent_data(data)

  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)

  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)

yaml.representer.RepresenterError: cannot represent an object: {'streamed': Stream([1024], float64, strides=None), 'history': {'extensions': []}, 'asdf_library': {'name'

/build/python-asdf-2.0.0/.pybuild/cpython3_3.6_asdf/build/asdf/stream.py:21: UnexpectedException
[...]
```

Build is done with Python 3.6, astropy 3.0, yaml 3.12 (Debian Buster/unstable).

**Comment by drdavella** [comment]
Closing this since I'm pretty sure the underlying issue will be the same as #499.
