### ISSUE TITLE
Importing asdf on python 2.7 and numpy 1.16.* fails

### ISSUE THREAD

**Issue by aprsa** [spacetelescope/asdf#707]
Running pip install asdf and importing with numpy 1.16.x on python 2.7 raises the following exception:

```
>>> import asdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/asdf/__init__.py", line 37, in <module>
    from .asdf import AsdfFile
  File "/usr/local/lib/python2.7/dist-packages/asdf/asdf.py", line 13, in <module>
    from . import block
  File "/usr/local/lib/python2.7/dist-packages/asdf/block.py", line 23, in <module>
    from .compat.numpycompat import NUMPY_LT_1_7
  File "/usr/local/lib/python2.7/dist-packages/asdf/compat/numpycompat.py", line 10, in <module>
    NUMPY_LT_1_7 = not minversion('numpy', '1.7.0')
  File "/usr/local/lib/python2.7/dist-packages/asdf/util.py", line 311, in minversion
    module = resolve_name(module_name)
  File "/usr/local/lib/python2.7/dist-packages/asdf/util.py", line 256, in resolve_name
    ret = __import__(str('.'.join(module_name)), fromlist=[attr_name])
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
    """)
RuntimeError: implement_array_function method already has a docstring
```

I see that the docs say that asdf now requires python 3.3, but if I downgrade to numpy 1.15, everything works just fine. Other places report this problem (https://github.com/numpy/numpy/issues/14012, https://github.com/numpy/numpy/issues/13430) but I don't see the conflict between cython and numpy on my side. Anyway, I figured I'd give you guys a heads up.

Also, asdf will fail at runtime (during write_to) if pytest is not installed. Perhaps pip should install pytest alongside asdf?

**Comment by jdavies-st** [comment]
Thanks for the heads-up.

Which version of `asdf` are you using?

Yes, I think `asdf 2.3.x` can still co-exist with these older dependencies, but we are no longer supporting `python 2.7`.

I would be interested in seeing the traceback for `write_to` depending on `pytest`.  That is unexpected, though we have seen something similar in `astropy` here

https://github.com/astropy/astropy/pull/9102

**Comment by eslavich** [comment]
I'm going to close this, since the pytest issue was discussed elsewhere, and we accept that asdf 2.4+ no longer supports Python 2.7.
