### ISSUE TITLE
asdf 2.4.2 dependency on pytest

### ISSUE THREAD

**Issue by aprsa** [spacetelescope/asdf#708]
Running python 3.7.3:

```
>>> import asdf
>>> asdf.__version__
'2.4.2'
>>> tree = {'test': 1.0}
>>> af = asdf.AsdfFile(tree)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/asdf/asdf.py", line 122, in __init__
    self._process_extensions(extensions)
  File "/usr/local/lib/python3.7/dist-packages/asdf/asdf.py", line 206, in _process_extensions
    self._extensions = default_extensions.extension_list
  File "/usr/local/lib/python3.7/dist-packages/asdf/extension.py", line 233, in extension_list
    self._extension_list = AsdfExtensionList(self.extensions)
  File "/usr/local/lib/python3.7/dist-packages/asdf/extension.py", line 226, in extensions
    self._load_installed_extensions()
  File "/usr/local/lib/python3.7/dist-packages/asdf/extension.py", line 197, in _load_installed_extensions
    ext = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/astropy/io/misc/asdf/extension.py", line 17, in <module>
    from .tags.coordinates.skycoord import *
  File "/usr/local/lib/python3.7/dist-packages/astropy/io/misc/asdf/tags/coordinates/skycoord.py", line 9, in <module>
    from astropy.table.tests.test_operations import skycoord_equal
  File "/usr/local/lib/python3.7/dist-packages/astropy/table/tests/test_operations.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

Installing pytest solves this issue.

**Comment by jdavies-st** [comment]
Thanks for the report.  This is the same issue reported here

https://github.com/astropy/astropy/issues/9099

for which a fix is almost done.

That said, this only shows up if `astropy` is installed and provides its ASDF extension, which is not required for your test case above.

So 2 ways to deal with this are

1) install `pytest`
or
2) uninstall `astropy`

Does that work for you?

**Comment by aprsa** [comment]
Our project depends on astropy so I can't (permanently) get rid of it, but installing pytest solves it indeed.

**Comment by jdavies-st** [comment]
Makes sense.  I suspect the fix on the astropy side will be out within a month.  Unfortunately nothing we can do in this repo, so I will close this issue and allow the linked issue above in the `astropy` repo to track progress on the fix.

Thanks!
